# Generated by Django 4.0.6 on 2024-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_seccion_alter_articulo_seccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palabraclave',
            options={'ordering': ['name'], 'verbose_name': 'Palabra Clave', 'verbose_name_plural': 'Palabras Claves'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='resumen',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
    ]
