# Generated by Django 4.0.6 on 2024-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_alter_palabraclave_options_alter_publicacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
