# Generated by Django 4.0.6 on 2024-05-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0005_imagen_delete_articlepicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Imágenes'},
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='pagina',
            new_name='pagina_inicio',
        ),
        migrations.AddField(
            model_name='articulo',
            name='pagina_fin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
